### ISSUE TITLE
Cask.lock

### ISSUE THREAD

**Issue by rejeep** [cask/cask#137]
Create `Cask.lock` file, just like Bundler, only that the version is minimum version.

**Comment by Fuco1** [comment]
I don't think this has any meaning in the current packaging environment where you always get latest and there is no upper version constraint.  Essentially a lock file is identical in result to new installation.

What I would like to see is maybe something like snapshots kept locally during `cask update` so that I can rollback if things break.  But that's a separate issue.

Regarding a lock file I would probably declare this a wontfix.

**Comment by conao3** [comment]
This would require significant additional code to use package.el, which is not cost-effective.
The community's assumption for Emacs packages will use the latest version due to MELPA.
