### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by patxoca** [cask/cask#272]
Trying to install cask from melpa stable yields: Package `package-build-0.1' is unavailable.

**Comment by rejeep** [comment]
Please provide some more information. What commands are you running? Also make sure you run all Cask commands with the `--debug` option to get a proper stacktrace.

Also, take a look at this: http://cask.readthedocs.org/en/latest/guide/troubleshoot.html

**Comment by patxoca** [comment]
I'm trying to install cask using the emacs package manager:

M-x package-install RET cask RET
Package `package-build-0.1' is unavailable
C-h v package-archives RET
 (("marmalade" . "http://marmalade-repo.org/packages/")
 ("gnu" . "http://elpa.gnu.org/packages/")
 ("melpa stable" . "http://melpa-stable.milkbox.net/packages/"))

**Comment by rejeep** [comment]
This will not work with Melpa stable only as `package-build` is not included (for some reason @purcell).

**Comment by purcell** [comment]
True. I'm hesitant to tag `package-build.el` while it's part of the main MELPA repo -- it needs to get split out into a separate repo, but I haven't the time to do that right now. I suppose I could upload `package-build.el` to Marmalade, but I'm wary of `package-archives` combinations which include MELPA Stable but not MELPA, because there are many packages missing from MELPA Stable which can lead to other packages being uninstallable.

**Comment by rejeep** [comment]
@purcell I say wait until you have time to do it right.

@patxoca I would use melpa (non stable) for now.
