### ISSUE TITLE
Running inside emacs

### ISSUE THREAD

**Issue by cpitclaudel** [cask/cask#330]
This piece of code is causing me headaches :)

```
    # If $INSIDE_EMACS is set, Cask is called from within Emacs, e.g. M-x
    # compile.  In this case, $EMACS may be set as well to a rather
    # meaningless value.  If $INSIDE_EMACS is set, we just ignore the
    # value of $EMACS.
    emacs = ENVB.get(b'EMACS') if b'INSIDE_EMACS' not in ENVB else None
    emacs = emacs or find_best_emacs()
    ensure_supported_emacs(emacs)
    return emacs
```
- Running `M-x compile RET EMACS=emacs24 cask build` compiles the current project for emacs25
- Running from the emacs shell (either `shell` or `eshell`) doesn't allow one to specify which version of emacs to use.

This forces me to use the regular command line, but then I can't jump to errors directly from the compile buffer. Is there a workaround?

**Comment by lunaryorn** [comment]
@cpitclaudel Not that I know of.  The situation around `$EMACS` is pretty unfortunate; it's almost entirely useless inside Emacs thus we can't really rely on its value, and we have no chance to figure out whether you explicitly overrode it, as in your `M-x compile` invocation.

We'd need to add an alternative `CASK_EMACS` variable probably.  Personally I never invoke Cask from inside Emacs, though :)

**Comment by phillord** [comment]
It would be good to get this fixed in Emacs. The "INSIDE_EMACS" behaviour is new in Emacs-25, so it's possible to change. Would something like "EMACS=~/path-to-current/emacs" make sense?

`M-x compile RET EMACS=emacs24 cask` should still work since it would reset the default emacs value.

At the moment, I am running cask of Emacs-25 trunk and cask is running Emacs-24.
