### ISSUE TITLE
Soft dependencies?

### ISSUE THREAD

**Issue by cpitclaudel** [cask/cask#334]
I'm trying to use cask to manage my personal `.emacs.d`. The main selling point for me is that it installs packages to different directories depending on the version of Emacs in use. This is great, because the binary formats of Emacs 24 and 25 are no compatible, and I use both with the same .emacs.d.

The only issue is that some packages are not available for Emacs 24.3, which I sometimes use (when working on remote machines, for example). In that case, Cask tells me:

```
Dependency company-quickhelp failed to install: Package `emacs-24.4' is unavailable
Output:
```

Is there a way to make Cask ignore these errors?

**Comment by lunaryorn** [comment]
@cpitclaudel No, unfortunately not.

I'm not sure though whether it's a good idea to ignore error.  I'd rather explicitly allow groups for specific Emacs versions.

**Comment by cpitclaudel** [comment]
I like the idea a lot.

Another direction entirely could be to turn the Cask DSL into an Elisp EDSL; that is, the contents of the Cask file would be a regular Elisp file, evaluated in a special context so that e.g. `(depends-on x)` would expand to `(push --dependencies x)` Then one could just wrap the relevant `depends-on` in the right conditional form.

**Comment by lunaryorn** [comment]
@cpitclaudel I'm very much in favour of having a statically analysable `Cask` file which would rule out an Elisp EDSL, but that's ultimately not my decision (/cc @rejeep).

I would rather only carefully extend the Cask DSL with features that are absolutely necessary—like dependencies for particular Emacs versions—in order to avoid feature creep, and the prevent bad practices from sneaking into Emacs Lisp packaging :sunglasses:

**Comment by rejeep** [comment]
> @cpitclaudel I'm very much in favour of having a statically analysable Cask file which would rule out an Elisp EDSL, but that's ultimately not my decision (/cc @rejeep).

I'm not very much against it, but I don't think we should use an "EDSL" as long as we can use simple macros to support edge-cases. In all years Cask has been around, there has not been any really good use case to add such a DSL.

In this case, I agree with @lunaryorn that adding a macro would be a better solution. For example:

```lisp
(source melpa)

(depends-on "foo")

(emacs 24
 (depends-on "bar"))
```

**Comment by Fuco1** [comment]
I was thinking for a long time about packages supporting multiple Emacs versions and the result is quite obvious after all: you shouldn't.

If you have a package that supports version 24.5 and versions 25.1 and the same code can't run on both, then you need to release **two** versions of your package each targeting the different platform.  This should be captured by the declared dependencies of the package.

This will require maintaining multiple branches in your project but that is in fact not that difficult, you would just cherry pick or rebase the patches which takes an extra 2 seconds (and github can even do that from the UI).

I started a similar issue https://github.com/cask/cask/issues/319 but I now think, nay, I KNOW, that is the wrong approach.  The fact that no other package manager does that also hints to that conclusion :)

This requires the archives (notably MELPA<stable>) to serve more than the latest version.  There is some discussion that could eventually result in MELPA stable doing that (the regular one, I'm afraid, is beyond saving).

**Comment by cpitclaudel** [comment]
> The fact that no other package manager does that also hints to that conclusion :)

Except they do, don't they? For example, Debian distinguishes between "Recommends" and "Requires", for example.

**Comment by Fuco1** [comment]
That seems to be a completely different case to me.

If we have a package that depends on unsatisfiable constraint that is not a recommendation but an error.

That means that somewhere we have to have additional checks on the environment and do something to prevent the package being broken.

A recommended dependency (what an oxymoron by the way) to me is one that one could `require` and it would work, or where one can check `if exists, then load`.  This would maybe be some sort of data files or plugins that enhance the original package which packaged separately to e.g. save space or give users better control.  In the case you mentioned it would never work and so we should not recommend it in an environment where it is impossible.

Now in the case of one package this seems like a minor issue, but Emacs being rather pathological we could find ourselves in a situation where there would be 5 Emacs versions needing different code and the sectioning won't save us: a package A that in older version would work fine with Emacs 24.3 might not anymore, and a package B that A depends on requires yet another version.  So we *could* install an older version of A but that would depend on a package B which in the latest doesn't work with our Emacs anymore => and we're out of luck.

The situation where packages try to support more than one platform now seems like so general an antipattern to me that I can't understand how things could still be working.  While some would call this "portability" I find it to be a relic of the past when formal dependency management was not yet invented.

Maybe as a practical example look at some packages by Drew Adams, they support Emacs way back to version 20 or 21.  The amount of conditional code is staggering.

**Comment by cpitclaudel** [comment]
> A recommended dependency (what an oxymoron by the way) to me is one that one could require and it would work, or where one can check if exists, then load. This would maybe be some sort of data files or plugins that enhance the original package which packaged separately to e.g. save space or give users better control. 

Or it could be a package that's not crucial, but is convenient to have.  For the original example here, I like to use company-quickhelp, so I put it in my config with a `no-error` require. I do want it to be installed, when it's available.

**Comment by Fuco1** [comment]
Yes that's fine, but that is a functionality from the point of view of the package in a working environment.  A "no error" require simply means that if it loads, then it should work.

My point is that the *package manager* should absolutely not care about multiple sets of dependencies for multiple environments.  The version of the package should provide a specification of what is required in each particular version (where a bump in a major dependency like OS or Emacs version should automatically means bump in the package version).  That is also why the dependency specification files (and lock files when available) are versioned.

MELPA for example has the same kind of problem: the recipe is versioned on the side of MELPA and not with the package.  Now if you want to build an older version, you're out of luck.  It is utterly impossible to do reliably because the file sets might be incompatible.

I am simply worried that with the already terrible situation in Emacs packaging accomodating these anti-patterns (which *are* convenient with respect to the status quo, I admit that) will make things even worse in the long run.

**Comment by phillord** [comment]
@Fuco1 Most of the MELPA recipe says how to get hold of the package source, so it has to be versioned melpa side. Having a build recipe as part of the package would be a good thing, though. MELPA does, indeed, conflate these, although most packages in MELPA just build in the standard way (byte-compile, autoload generate).

The problem at the moment is surely that *Emacs* does not support multiple versions of packages. You cannot post an Emacs 24.5 and an Emacs 25 version onto the same version of a ELPA repo, unless you do something like seq.el has done (which packages seq-24.el and seq-25.el, then requires the right one at run time). But this *only* works because seq-24.el and seq-25.el have the same dependencies (i.e. none, or rather just dependencies in core Emacs. Without this, you'd need some sort of conditional dependency mechanism.

Still, I agree with you, fudging it seems a bad approach, and attacking the core (pun intended) problem is right. It's not fixable for Emacs-25, but it could be fixed for Emacs-26. Want to?

**Comment by Fuco1** [comment]
@phillord Hm, why would it be impossible? Have a version 1 of seq with dependency on E24, and have version 2 with dependency on E25.  Then require the one your Emacs supports.  AFAIK package.el can have multiple versions of the same package (as a installable candidate, not as installed version).

What it doesn't support though (I think) is conditionals on the versions, so I think we can't say `(depends-on "seq" "~1.0")` (which would mean `>=1.0 <2.0`).  This would then install the correct version.

This would mean people would have to maintain two (or multiple) versions, in practice this is not such a big deal: usually you would only provide bug-fixes or critical patches to the older maintenance versions and add features only to the latest branch.  After a couple releases you could EOL the oldest versions.

Concerning `seq`, it is perhaps not a "standard" package in a way that it is actually part of the distribution (so you wouldn't bundle seq-24 with Emacs 25, or?).  So there I don't understand why there are two versions at all.  Or is it for people with older Emacsen so that they can install it from ELPA? If so then the first point about version constraints applies.

I have in writing a rather elaborate article on the state of the packaging and what needs to happen to move to the next level, and I will be willing to help out, because frankly, it is getting ridiculous :D

The jump Emacs ecosystem did after package.el and MELPA came to the scene was *enormous* and I feel that when/if we get this right (well... better) it can help even more to move the Emacs world forward.

**Comment by phillord** [comment]
Matus Goljer <notifications@github.com> writes:

> @phillord Hm, why would it be impossible? Have a version 1 of seq with
> dependency on E24, and have version 2 with dependency on E25.  Then require
> the one your Emacs supports.  AFAIK package.el can have multiple versions of
> the same package (as a installable candidate, not as installed version).


AFAIK, package.el considers version numbers numerically. So, Emacs 24 is
going to think that version 2 outdates version 1 and will try to upgrade
to it.

We need Emacs 24 to NOT see version 2, I think. I do not know whether
this is possible, but it may be.

> What it doesn't support though (I think) is conditionals on the versions, so I
> think we can't say `(depends-on "seq" "~1.0")` (which would mean `>=1.0
> <2.0`).  This would then install the correct version.
>
> This would mean people would have to maintain two (or multiple) versions, in
> practice this is not such a big deal: usually you would only provide bug-fixes
> or critical patches to the older maintenance versions and add features only to
> the latest branch.  After a couple releases you could EOL the oldest versions.

Yes, I'd agree with all of this. It might take a bit of thinking about
how to add this in a backward compatible way (I mean, it would be good
to add it to Emacs-26, so that Emacs-25 still gets the right thing
without supporting this conditionality).


> Concerning `seq`, it is perhaps not a "standard" package in a way that it is
> actually part of the distribution (so you wouldn't bundle seq-24 with Emacs
> 25, or?).  So there I don't understand why there are two versions at all.  Or
> is it for people with older Emacsen so that they can install it from ELPA? If
> so then the first point about version constraints applies.

seq is part of Emacs-25. Having it in ELPA means that you can upgrade
seq.el on Emacs-25 independent of the Emacs-25 upgrade cycle. The
situation is equivalent to org-mode which is in core and on ELPA.

>
> I have in writing a rather elaborate article on the state of the packaging and
> what needs to happen to move to the next level, and I will be willing to help
> out, because frankly, it is getting ridiculous :D
>
> The jump Emacs ecosystem did after package.el and MELPA came to the scene was
> *enormous* and I feel that when/if we get this right (well... better) it can
> help even more to move the Emacs world forward.


I'd agree with this also. package.el has been fantastic; multi-version
and core upgrading are two things that need fixing.

**Comment by bendikro** [comment]
Is there any workaround to handle this error for unsupported emacs versions?

**Comment by dickmao** [comment]
> I was thinking for a long time about packages supporting multiple Emacs versions and the result is quite obvious after all: you shouldn't.

That's not obvious to me.  In any case, the world has moved on from 2016.

Contrary to the cask quickstart docs, I don't recommend cask as a package maintenance tool, i.e., running `cask-initialize` in your `.emacs`.  It's better just as a package development tool like virtualenv (as advertised).
