### ISSUE TITLE
Handle bash scripts in `/bin` directories for installed dependencies for Windows

### ISSUE THREAD

**Issue by howdoicomputer** [cask/cask#345]
If you're running Windows and you run `cask exec ert-runner`, or any dependency with an executable bash script in the `bin` directory, you'll get an error message because cask can't find a file that is ~executable by the OS~.

I can get things to run if I lay down a batch file that execs bash so I guess that means that a potential solution is to have cask detect if bash is installed on Windows and then exec that. Thoughts? I don't mind working on and submitting a PR for this.

**Comment by rejeep** [comment]
Doesn't sound like a Cask issue? Cask exec will set up the environment and then just run an external command.

Can you run any command using Cask exec? For example `cask exec some-other-windows-command`

I don't know anything about windows, but I'm sure there's a proper solution to it.

**Comment by lunaryorn** [comment]
@howdoicomputer I don't think that this is a Cask issue, too.  We don't do magic when running package commands; Cask should pick up windows runner scripts just fine.

The problem is rather that `ert-runner` and similar packages don't include an Windows runners, i.e. no BAT files or something similar.

@rejeep What do you think about extending `exec`'s semantics a bit?  Look, we spawn a batch instance for Cask anyway, so why not reuse it?  

Why—instead of trying to run `bin/ert-runner`—not try to load `bin/ert-runner.el` first and look whether there's `ert-runner/main` inside, and if so, run that function with a list of command line args?  And only try to run an external command if this special entry point is absent?

A Cask-specific entry point would also allow us to pass a more elaborate environment down to the tool.  Ert-runner could have access to the loaded `Cask` bundle for instance, or to the `Cask` metadata.  We could go as far as to let external tools add their own metadata to `Cask` files then, i.e. 

```elisp

(package …)
(ert-tests "test/*-test.el")
```

where `ert-runner` would then look at `ert-tests` to find its test files.

**Comment by rejeep** [comment]
```lisp
(defun ert-runner/main (&public static void main[] args) ...)
```

Like it! 👍 😄 

On a more serious note, it doesn't sound like the worst idea. But if we do this, I would like it to be a non-Cask standard, but a more general "standard". Any tool, like Cask, could use this format to run packages controlled by binaries.

**Comment by lunaryorn** [comment]
Sure I don't think we should force Cask upon client tools; the entry point should be generic.

But I also don't think that we should prevent client tools from accessing Cask if they want, and I think it'd be cool to expose Cask's metadata to client tools.  

Ert-runner would not require Cask of course, but if it found tests in Cask metadata wouldn't it be great if it ran those?

**Comment by rejeep** [comment]
My point here is that it doesn't have to be Cask-metadata, it can be just metadata and sometimes it is from Cask and other times from some other tools. We don't need to use "cask" in any of the name properties. Instead of `cask-path`, we'll call it just `path`. Makes sense?

**Comment by lunaryorn** [comment]
I'm not sure whether we can find any kind of metadata format that'd make sense for all sorts of tools.

I'm not sure what you're referring to with `cask` and `cask-path`; but assuming that we load the runner into the Emacs instance that runs Cask, we can't prevent access to Cask anyway.  After all, there's no global namespacing in Emacs, so any of Cask's own variables will be visible to the client tool anyway.

So we might as well make them public right away, and document them.  

I wasn't thinking of anything fancy, and I'd not pass metadata down to the `main` function; but I'd document that there are a couple of global variables (e.g. `cask-current-bundle`, etc.) that are bound to certain values when the `main` function runs within Cask.  Client tools can then decide themselves whether they'd like to (optionally) become aware of Cask or not.

**Comment by rejeep** [comment]
I was thinking of something like this:

```lisp
(require 'cask)
(cask-setup (plist-get metadata :path))
```

So instead of exposing the bundle object, you pass the path as metadata and then the underlying project can require Cask and create their own bundle.

**Comment by dickmao** [comment]
> Why—instead of trying to run bin/ert-runner—not try to load bin/ert-runner.el first and look whether there's ert-runner/main inside, and if so, run that function with a list of command line args? And only try to run an external command if this special entry point is absent?

Cask is already arcane enough without adding further "how-was-i-supposed-to-know-that" hooks like the aforementioned.
But in any case, such augmentation of cask's special logics is besides the point that we only guarantee cask to find what's in the output of `cask path`.  Anything missing would need to preface the cask invocation with `PATH=missing:${PATH} cask exec ...`
