### ISSUE TITLE
Cask fails to recognize it is inside emacs in emacs 25 

### ISSUE THREAD

**Issue by joelmccracken** [cask/cask#371]
Looks like it is this FN: 

```
def inside_emacs_24():
    """Whether Cask is running inside Emacs-24.

    Emacs 24 is rather inconsistent in its use of the ``$EMACS`` and
    ``$INSIDE_EMACS`` environment variables, so we try here to test if Cask is
    being run inside Emacs (either in a shell or with ``M-x compile``).

    Return ``True`` when running in Emacs 24, ``False`` otherwise.

    """
    ## are we inside Emacs at all
    return (b'INSIDE_EMACS' in ENVB and
            ## M-x compile in Emacs-24 sets INSIDE_EMACS to exactly 't'
            (ENVB.get(b'INSIDE_EMACS') == b't' or
             ## while M-x shell sets it to a string, starting with the
             ## version number
             ENVB.get(b'INSIDE_EMACS').startswith(b'24')))
```

relevant environment variables:

```
env | grep EMACS
EMACS=25.1.1 (term:0.96)
INSIDE_EMACS=25.1.1,term:0.96
```

**Comment by willbush** [comment]
I was going to open the same issue and I had already typed it out, but then I noticed this one exists. So I'm just going to paste it here.

#### Description

I'm getting the same issue described in the documentation in
[finding-emacs](http://cask.readthedocs.io/en/latest/guide/usage.html?highlight=CASK_EMACS#finding-emacs):

"Exceptionally, if you are launching cask inside Emacs 24 either from an
internal shell or M-x compile, then Emacs uses EMACS in a way which conflicts
with cask, in which case you can use the environment variable CASK_EMACS
instead. With Emacs 25, EMACS can be used as normal."

However, my emacs version is 25.3.1. I don't exactly what the issue was with
emacs 24, but in my case `EMACS` is set to `25.3.1 (term:0.96)` and
`https://github.com/cask/cask/blob/master/bin/cask` seems to expect it to be a
path to emacs.

See the following commands I executed from a shell within emacs:

```bash
$ cask
$ mkdir test
$ cd test
~/test$ cask
cask: error: Emacs does not exist at 25.3.1 (term:0.96).  Did you install Emacs?
~/test$ echo $EMACS
25.3.1 (term:0.96)
~/test$ export EMACS="$(which emacs)"
~/test$ echo $EMACS
/usr/local/bin/emacs
~/test$ cask init
~/test$ ls
Cask
```

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: nil (rev. 2e8727a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown html emacs-lisp
          (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "johan-tibell" haskell-compile-cabal-build-command "stack build")
          rust csharp yaml
          (auto-completion :variables auto-completion-private-snippets-directory "~/dotfiles/spacemacs/snippets/")
          git helm neotree
          (org :variables org-enable-github-support t)
          (shell :variables shell-default-height 30 shell-default-position 'bottom)
          spell-checking syntax-checking semantic)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Work Around

Set the `CASK_EMACS` environmental variable to the path of emacs as described in
[finding-emacs](http://cask.readthedocs.io/en/latest/guide/usage.html?highlight=CASK_EMACS#finding-emacs).

**Comment by sambrightman** [comment]
I have forgotten the complicated history of this, and have just re-skimmed #335 - I'm left with the impression that `CASK_EMACS` is the recommended way to go. Is there a problem with the workaround?

I'm also running 25.3.1 and do _not_ see `EMACS` defined in a shell. Are you perhaps using `M-x term` as mentioned at the end of the PR? @phillord did you ever fix this or it still a known issue?

**Comment by willbush** [comment]
I wasn't using `M-x term`. I was using an internal shell in emacs. If nothing
else changes, then I think at the least the documentation should be updated to
mention that `CASK_EMACS` is recommended.

From the PR that you linked and the documentation I get the impression the
understanding is that `EMACS` environmental variable should be a path to the
emacs executable in emacs 25, but in emacs 24 it is unreliable. However, it just
seems unreliable either way.

Maybe only this needs to be updated:

>Exceptionally, if you are launching cask inside Emacs 24 either from an internal shell or M-x compile, then Emacs uses EMACS in a way which conflicts with cask, in which case you can use the environment variable CASK_EMACS instead. With Emacs 25, EMACS can be used as normal.

**Comment by sambrightman** [comment]
I'll have to read in a little more detail, but that sounds likely. Can you provide exact steps to reproduce? I don't often use a shell inside Emacs, but when I do I get the correct value.

**Comment by phillord** [comment]
This one went backwards and forwards so often than I am left with no clear idea. Neither Emacs-25 nor Emacs-26 has EMACS, but does have INSIDE_EMACS. However, they do not conflict with Cask's use of EMACS. So, cask will *not* work out which Emacs you are inside of (except by chance), but will obey the EMACS variable, if set either inside or outside Emacs. 

Cask doesn't need to know it is inside Emacs-25 AFAICT, only Emacs-24.

**Comment by phillord** [comment]
Actually, need to update the documentation to change CASK_EMACS to "historical" and change the Emacs-25 reference to "Emacs-25 or later". I'll do that.

**Comment by phillord** [comment]
Okay, so this is a problem specific with term.

Stefan fixed the problem here: http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=beaab898968caf8b243a33d24824d430fabc31fc

But, unfortunately, Paul rebroke it http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=73d213f2816876fe9c6c429e75a3be5454a42b34

And then mostly unbroke again, here http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=a1f221bd82eb4393ccba83a361b435a4992b532a partly as a result of me complaining https://debbugs.gnu.org/cgi/bugreport.cgi?bug=20484#108

So, the problem is specifically with M-x term. For everything else, the documentation is correct. Unfortunately, this is true for all of Emacs-25 and Emacs-26 is in release candidate. So solution:

1) I need to see if we can remove the M-x term hack from Emacs-26.2 and later.
2) We extend the heuristic for `inside_emacs_24` to be catch M-x term. We could do this by seeing if EMACS starts with "2" rather than "24", or if it contains "(term:".

Or, as an alternative solution, two or three years after I first tried to fix this:
3) Give up and use vim instead.

Answers on a postcard please.

**Comment by sambrightman** [comment]
Only @willbush says he wasn't using `M-x term` when he had the problem.

If the original debate/resolution you linked to from 2015-2016 was about `M-x term` only, then it did look broken again when I tested it regarding this issue.

Is there a problem with just recommending `CASK_EMACS` for all versions?

**Comment by phillord** [comment]
@sambrightman I think @willbush is wrong.

     in my case EMACS is set to 25.3.1 (term:0.96)

The `term:0:96` thing comes from term, and not from anywhere else. AFAICT, only, M-x term sets EMACS now (from Emacs-25 onward).

**Comment by willbush** [comment]
It's possible something else I have was using M-x term. I didn't even know that existed until you guys mentioned it. I'll try to get steps to reproduce the issue and post them here later.

**Comment by phillord** [comment]
Would be grateful to have a reproduction -- I want to kill this bug in Emacs and if it is somewhere else other than M-x term, I'd like to know.

**Comment by phillord** [comment]
http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=6fcab83600317e94ea7b915da7730a8c7e50226d

Fix for term.el is in Emacs-27. @willbush if you managed to find a reproduction that would be great. Otherwise, I will update the doc to describe when to use CASK_EMACS. Unfortunately, this means that CASK_EMACS will need to be in place for quite a few years yet.

**Comment by phillord** [comment]
Thanks for the reproduction, it's very clear (esp. as I've not used spacemacs before).

So the shell is running under term. I didn't know spacemacs made that the default. So, at least we know the issue now. It will disappear in Emacs-27 thanks to Paul Eggert's update, at least when bash is recent. I will update the cask docs to reflect.

**Comment by sambrightman** [comment]
Is there any reason for us not to recommend `CASK_EMACS` as the primary method? That’s seems much clearer and more reliable, but doesn’t preclude trying to fix the default behaviour.

**Comment by willbush** [comment]
Awesome, thanks for your help!
