### ISSUE TITLE
Cask doesn't appear to allow for manually maintained package metadata in its workflow.

### ISSUE THREAD

**Issue by cowboyd** [cask/cask#381]
Using header comments is a great way to manage dependencies inside of a single file, and Cask supports this workflow in a very straightforward way with the `package-file` directive. However, if your package has a lot of dependencies, then it starts to become unwieldly. The dependency header must appear on a single line and so with a configuration package like we're developing that has around 40 dependencies, it's untenable (I haven't found a way to make them multi-line)

For that reason, I wanted to manage dependencies in elisp. My first attempt was to invoke the `package-file` directive with the package descriptor:

```elisp
(package-file "my-pkg.el")
```
but that assumed it was a package file, not a descriptor. Failing that, I used a combination of `package` and `depends-on`:

```elisp
(package "my")
(depends-on "foo")
(depends-on "bar")
```
This worked great in development, but when it came time to deploy the package, the `my-pkg.el` generated by `cask package` did not actually include `foo` and `bar` in its list of dependencies.

This makes it difficult to work with manually maintained multi-file package metadata. Some possible remedies to this are:

1. make the `package-file` directive "smart" so that if it ends in `-pkg.el`, then it treats it as a package descriptor
2. Add a new directive: `package-descriptor` that assumes that allows you to incorporate a package descriptor directly.
3. If you use a combination of `package` and `depends-on` directives, then make sure the resulting package descriptor generated by `cask package` contains those dependencies.

I'd be happy to take a stab at adding that if I can get some guidance as to the best option. I'm leaning towards (2) since it seems like the most intuitive.

**Comment by cowboyd** [comment]
Regardless of which way we go, it does seem like not including the dependencies from this construct:

```elisp
(package "my")
(depends-on "foo")
(depends-on "bar")
```
in the generated package descriptor Is a bug?

**Comment by purcell** [comment]
I *think* that if you use `package-file` with your main `.el` file _and_ you also include `"*.el"`, then you should be able to put your metadata in a `-pkg.el` file. I suspect this will work, because cask uses `package-build` under the covers, just like MELPA.

**Comment by cowboyd** [comment]
Thanks @purcell! That _kinda_ works, except that it requires the version header to live in the main `.el` and then the rest of the metadata in the package descriptor. Ideally, I'd like to just control package metadata in a single place.

**Comment by purcell** [comment]
Hmm, that's weird, and is presumably a Cask quirk, then.

**Comment by sambrightman** [comment]
I'm still trying to puzzle through what is going on here and what the best solution is. Some notes:

1. `lisp-mnt.el` indeed prevents newlines in comment headers. If there is a desire to allow multi-line dependencies via docstrings, you'd have to look into why that has been disallowed there.
2. Fixing the `depends-on` case seems desirable to me and sounds like your favoured solution too. From what I can tell, this is not due to Cask but rather `package-build.el`, which always gets dependencies from the docstrings.
3. Likewise, `package-build.el` requires version before parsing the docstrings (as you found). It's not really clear to my why this is - ability to checkout the package is mentioned, and there appears to be some ability to update the version.

As I mentioned in #383 I don't think it's great to expand the DSL/API if there are better solutions. However, there currently don't seem to be. @purcell can you shed any light on 2) & 3)? Would it make sense for `package-build-package` to accept dependencies directly?
