### ISSUE TITLE
Cask recently started setting the wrong $PATH on Travis

### ISSUE THREAD

**Issue by DarwinAwardWinner** [cask/cask#399]
My package has been using evm and cask without issue on Travis for a little over a month. But apparently something changed in the past few weeks that causes cask to ignore the evm-installed emacs version. The reason seems to be that cask is adding `/usr/bin/` to the front of `$PATH`, which means that the system `/usr/bin/emacs` takes precedence over the evm copy of Emacs. This is demonstrated in the latest Travis build log: https://travis-ci.org/DarwinAwardWinner/ido-completing-read-plus/jobs/277499771

In that build, I print out `$PATH` with and without cask:

```
$  echo $PATH
/home/travis/.cask/bin:/home/travis/.evm/bin:...
$ cask exec sh -c 'echo $PATH'
/usr/bin:/opt/pyenv/libexec:/opt/pyenv/plugins/python-build/bin:/home/travis/.cask/bin:/home/travis/.evm/bin:...
```

I'm not sure what cask was adding to $PATH back when my build used to work, since I only added that debug code once the build failures started.

Unfortunately, there also appears to be a separate issue that prevents cask's `--verbose` and `--debug` options from working, so I was unable to add them to the cask invocations in my `.travis.yml`. Specifically, if the first argument to cask starts with a dash, cask insists on interpreting *every* argument that begins with a dash anywhere in the command. Example:

```
$ cask exec sh -c 'echo hello'
hello
$ cask --verbose exec sh -c 'echo hello'
Option ‘-c‘ not available
$ cask --debug exec sh -c 'echo hello'
Debugger entered--Lisp error: (error "Option ‘-c‘ not available")
  signal(error ("Option ‘-c‘ not available"))
  error("Option `%s` not available" "-c")
  commander--handle-options(("--debug" "exec" "sh" "-c" "echo hello"))
  commander-parse(("--debug" "exec" "sh" "-c" "echo hello"))
  (if commander-parsing-done nil (commander-parse (or commander-args (cdr command-line-args-left))))
  eval-buffer(#<buffer  *load*> nil "/home/ryan/.cask/cask-cli.el" nil t)  ; Reading at buffer position 12803
  load-with-code-conversion("/home/ryan/.cask/cask-cli.el" "/home/ryan/.cask/cask-cli.el" nil t)
  load("/home/ryan/.cask/cask-cli.el" nil t t)
  command-line-1(("-scriptload" "/home/ryan/.cask/cask-cli.el" "--" "--debug" "exec" "sh" "-c" "echo hello"))
  command-line()
  normal-top-level()
```

**Comment by DarwinAwardWinner** [comment]
It just occurred to me that it's possible that nothing changed in Cask, but maybe Travis just switched to a new filesystem image that happens to have an Emacs in `/usr/bin/` when the old image did not, thus revealing the problem. Or any number of other scenarios. Also, here's the link to my .travis.yml: https://github.com/DarwinAwardWinner/ido-completing-read-plus/blob/bleeding-edge/.travis.yml

**Comment by davidshepherd7** [comment]
I'm seeing the same problem in a lot of different packages. I've done some digging but I haven't found a solution yet. Here's what I did find:

It looks like travis [added various versions of emacs to their images](https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch) sometime in June, so maybe we are running that version somehow.

Some investigations into where cask's path comes from:

1. `cask` is a python script
2. to get the path for `cask exec` `cask` calls `cask path`
3. `cask path` constructs the path [here](https://github.com/cask/cask/blob/master/cask.el#L670) by prepending paths to cask-controlled binaries to the current `exec-path` variable.

Since the whole thing is kicked off from python the different path inside `cask exec` is probably because `$PATH` is different inside python. It looks like [travis has recently had some problems with paths python](https://github.com/travis-ci/travis-ci/issues/8048), I'd be willing to bet that this is related somehow. One of the recommended workarounds in that thread is to prepend `/usr/bin` to the path when running python commands, which is exactly the problem your log shows!

I added `/usr/bin/env python -c "import os; print(os.environ['PATH'])"` to my `.travis.yml` and the `/usr/bin` path showed up [there](https://travis-ci.org/davidshepherd7/electric-operator/jobs/278904080). This is even true if you set travis to use the legacy infrastructure, so we can't work around it by doing that.

Travis recently (6th September) changed something to ["ensure `pyenv versions` works correctly"](https://docs.travis-ci.com/user/build-environment-updates/2017-09-06/#Changed). So whatever that change is it's probably the culprit. I couldn't find any code, commits or PRs related to this :disappointed:.

Setting `CASK_EMACS` is also not quite good enough, that doesn't work for commands of the form `cask exec emacs ....`, because it still picks emacs using the `$PATH` inside cask.

Also potentially relevant: https://github.com/travis-ci/travis-ci/issues/8363

**Comment by davidshepherd7** [comment]
I've also found [this issue](https://github.com/pyenv/pyenv/issues/789), it looks like pyenv is our culprit!

From the sounds of it: when you set pyenv to use the system version of python it prepends `/usr/bin` to the path!

**Comment by DarwinAwardWinner** [comment]
Well, with that hint, one way to work around this is to change the first line of the cask script to `#!/usr/bin/python` in order to bypass pyenv. This should be fine since cask uses only core Python modules.

**Comment by davidshepherd7** [comment]
An alternative fix is to add

```
# Remove pyenv from the path, work around for https://github.com/cask/cask/issues/399
export PATH=$(echo $PATH | tr : "\n" | grep -v /opt/pyenv/shims | tr "\n" :)
```

to Rejeep's `travis-evm-cask` script that most `.travis.yml` files use. I've made a [fork](https://gist.github.com/davidshepherd7/2f634782ad14a1ce91a70adfeae44bf6) of the gist with the fix. 

This way is guaranteed to not break cask for anyone (e.g. people who have python installed somewhere else), but it does mean that we only fix it for people who are using this script.

**Comment by vermiculus** [comment]
Sorry for my mess, folks – I've been trying to implement a workaround for this issue, but I've been unwittingly clogging it up in doing so.

Clearly, though, I've been unable to resolve this issue. Can someone help me out? No matter what I do, `cask exec emacs --version` always gives me 24.3 (whereas my tests fail on anything <25).

I'm installing both emacs and cask via https://github.com/flycheck/emacs-travis.

**Comment by davidshepherd7** [comment]
Unfortunately the fix only seems to work for some places, I'm trying to investigate now but it's quite tricky to test because everything needs to run on Travis... Hopefully we'll get there!

**Comment by davidshepherd7** [comment]
@vermiculus Have you tried using [this](https://github.com/cask/cask/issues/399#issuecomment-331640427) workaround?

**Comment by vermiculus** [comment]
@davidshepherd7 [Yes; it failed](https://travis-ci.org/vermiculus/magithub/jobs/281942955#L937) ☹️

**Comment by davidshepherd7** [comment]
@vermiculus I think that might be a different problem. It looks like you're [invoking cask through a symlink](https://github.com/flycheck/emacs-travis/blob/master/emacs-travis.mk#L116), but [this code](https://github.com/cask/cask/blob/master/bin/cask#L43) doesn't seem like it will support that.

You could try running cask using the full path instead (something like `~/.cask/bin/cask` with that makefile).

**Comment by vermiculus** [comment]
It did *just* stop working, though -- it's worked in the past using just `cask`.

**Comment by davidshepherd7** [comment]
Yeah, it would be weird if that is the problem, but that was the only idea I had.

**Comment by davidshepherd7** [comment]
Despite the strangely failing test fix seems to have worked, [my package's tests](https://travis-ci.org/davidshepherd7/electric-operator) are back on the correct emacs versions. :tada:
