### ISSUE TITLE
Remove temporary package-build kludge

### ISSUE THREAD

**Issue by Fuco1** [cask/cask#464]
See comment from @tarsius https://github.com/melpa/package-build/pull/29#issuecomment-508085859

**Comment by tarsius** [comment]
What I wanted you to do is what had already been done in #429. I think I was not aware that had already been done at that time and it seems that you had a look and noticed that it had already been done and concluded that I was asking you to remove that kludge eventually.

Anyway... don't remove it. Maybe at some later time.

What I would like to know at this time is if it is finally safe to remove the following from `package-build.el`:

```elisp
(define-obsolete-function-alias 'package-build-package 'package-build--package
  "Package-Build 2.0.

The purpose of this alias is to get Cask working again.

This alias is only a temporary kludge and is going to be removed
again.  It will likely be replaced by a function with the same
name but a different signature.

Do not use this alias elsewhere.")
```

On Cask's `master` branch `package-build--package` is being used now, so that is good. But no Cask version has been released since 4f759696e502028adb839a4204921a026bdfe608, so this would break the latest released Cask version, right?

Please consider creating a new release.

**Comment by conao3** [comment]
I don't know how it happened as I recently joined the project, but I guess we need a just new release?
Thanks for the advice, tarsius!

**Comment by tarsius** [comment]
Thanks!
