### ISSUE TITLE
How to define package archives priority?

### ISSUE THREAD

**Issue by YorkZ** [cask/cask#486]
I have a local package archive in a directory on my local system. In this directory I have a package `foo`. However, package `foo` is also in, say, `melpa`. If `melpa` has a higher version of `foo` than the one in my local package archive, `cask` will always install package the higher version of `foo` from `melpa`. What I need is that `cask` would install the lower version of `foo` from my local package archive. How can I achieve this.

Emacs `package.el` has the variable `package-archive-priorities` for this purpose, therefore I'm wondering if it would be possible for `cask` to allow user to somehow set the Emacs variable `package-archive-priorities`.

**Comment by conao3** [comment]
Wow, I don't know ever that variable.

However, for me, this problem has been resolved.
I maintain my own MELPA (called [CELPA](http://celpa.conao3.com/)) that registers some fork of MELPA package, but this fork is always somewhat higher than the MELPA version number. (see [source](https://github.com/conao3/celpa/commit/d616368aab97f67109a105e21cbaa0c8c5eb81a2))
This will allow you to achieve the desired behavior.

**Comment by YorkZ** [comment]
Interesting idea, so you automatically add 1000  to the minor version number right? But what if the upstream changes the major version number?

Is `CELPA` your fork of `MELPA`?

An off-topic question, where is http://celpa.conao3.com hosted? I ask because I'm also interested in taking your approach. I would greatly appreciate it if you could introduce a bit more about your entire process.

Thanks

**Comment by conao3** [comment]
> But what if the upstream changes the major version number?

Nothing bad. It doesn't matter if upstream changes the major version.
To make sure that MELPA version is always installed even if developer change the major version, MELPA ignores upstream's major version and uses an unusually large version based date.
Due to this mechanism, MELPA is installed in preference to ELPA, even if the same package is available in ELPA and MELPA.
But I don't know about the variables you mention, so I'm not sure about that.

Now, MELPA is overwritten by a version that is usually unthinkable. I'm adding a fixed value to it so it will always be perceived as being a newer version than MELPA.

> Is CELPA your fork of MELPA?

Yes, but It complements MELPA; I register my packages before they are registered to MELPA, and I register other people's forked packages.
Once they are registered with MELPA, they are usually removed from CELPA.
It's basically a personal thing, but others can use it too.

> An off-topic question, where is http://celpa.conao3.com hosted? I ask because I'm also interested in taking your approach. I would greatly appreciate it if you could introduce a bit more about your entire process.

OK. GitHub Actions build CELPA every 30 minutes, and then the finished product is just deployed to my hosting service server via `rsync`.

**Comment by YorkZ** [comment]
> OK. GitHub Actions build CELPA every 30 minutes, and then the finished product is just deployed to my hosting service server via rsync.

Does GitHub build CELPA even if there are no changes? Is your hosting service a free one or a paid one?

**Comment by conao3** [comment]
> Does GitHub build CELPA even if there are no changes?

Yes, GitHub Actions every 30 minutes with no conditions. [Actions Log](https://github.com/conao3/celpa/actions)

> Is your hosting service a free one or a paid one?

Paid one.

**Comment by conao3** [comment]
Close for now, for out of Cask requirements.
