### ISSUE TITLE
Release command

### ISSUE THREAD

**Issue by rejeep** [cask/cask#95]
Add release command
### spec
- Will only support major, minor and patch, no pre releases.
- Usage: `cask release --major` to release major
- Usage: `cask release --minor` to release minor
- Usage: `cask release --patch` to release patch
- Create git tag (if git repo).
- Files with package header versions are updated
- `Cask` file is updated
### questions
- Only create tag if `--tag` option?

**Comment by phillord** [comment]
Can I add "disable melpa in favour of melpa stable in cask file" to the spec? I've just hit a bug in a release of one of my packages which would have been caught by this!

**Comment by rejeep** [comment]
I'm not sure I understand how this is relevant to this issue?

**Comment by phillord** [comment]
When I release a package, I want it to not depend on snapshots of other packages. So, for release, in the ideal world I want to do: disable melpa (which is full of snapshots), test, remove "-snapshot" suffix, and bump to new version if necessary, commit, tag, test again, bump version to -snapshot with to prepare for next iteration.

But the main reason for disabling (or at least emitting a warning) about melpa is prevent a release containing a dependency only in melpa, and not in stable.

**Comment by lunaryorn** [comment]
@phillord I think you should just use `(source melpa-stable)` in your `Cask` file right away.  What's the point of depending on snapshots during development if you'd like to prohibit snapshots when making releases?

**Comment by phillord** [comment]
Well, releases should have only released dependencies because otherwise
the release becomes unstable and can change behaviour if dependencies
change. Allowing only released dependencies prevents this (except for
the case that I have just hit where a dependency did not exist and the
main package can be fixed).

Between releases, I need to depend on snapshots so that I can pick up
shapshots of the other dependencies where they have new features I need.
Mostly, this is where I control the dependencies also. So, my package
"lentic" depends on "m-buffer". When a feature in lentic means I need to
extend m-buffer, I add that functionality to m-buffer, push, move lentic
over to (source melpa) and then complete.

I assumed this is how everyone does it. Obviously I was wrong.

Phil

**Comment by dickmao** [comment]
This is an idea too far ahead of its time.
